# Fase 3: Diseño Base de Datos

In [1]:
import mysql.connector                 # Importamos las librarias necesarias
from mysql.connector import errorcode
import pandas as pd
import csv

In [60]:
df_hr = pd.read_csv("clean-data/clean_df_hr.csv")

In [17]:
with open("clean-data/clean_df_hr.csv", newline="", encoding="utf-8") as csvfile:     # usamos rutas relativas para para asegurar portabilidad y evitar dependencias del entorno local
    reader = csv.DictReader(csvfile)

In [49]:
try:
    # nos conectamos al servidor de mysql, no especificamos schema porque vamos a crearlo
    
    cnx = mysql.connector.connect(
        user='root',
        password= input('Escribe aquí tu contraseña:'),
        host='127.0.0.1'
        # auth_plugin = 'mysql_native_password'
    )
    print("¡Conexión exitosa a MySQL!") #
except mysql.connector.Error as err:
    # Si es un error de acceso denegado (ej. contraseña o usuario incorrecto)
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Algo está mal con tu nombre de usuario o contraseña.") #
    # Si la base de datos no existe
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        print("La base de datos no existe.") #
    # Para cualquier otro tipo de error
    else:
        print(err) #
        print("Código de Error:", err.errno) #
        print("SQLSTATE", err.sqlstate) #
        print("Mensaje", err.msg) #

¡Conexión exitosa a MySQL!

In [50]:
mycursor = cnx.cursor() # Iniciamos el cursor
mycursor.execute("CREATE SCHEMA IF NOT EXISTS hr_ABC;") # creamos schema
mycursor.execute("USE hr_ABC")

In [ ]:
# esto lo mantenemos??
mycursor.execute("SET FOREIGN_KEY_CHECKS = 0")

tablas = [
    "job_details",
    "career_history",
    "compensation",
    "performance_satisfaction"
]

for t in tablas:
    mycursor.execute(f"DROP TABLE IF EXISTS {t}")

mycursor.execute("SET FOREIGN_KEY_CHECKS = 1")
cnx.commit()

print("Tablas eliminadas.")

Tablas eliminadas.

In [6]:
df_job_details = df_hr[["department","job_role","job_level","business_travel","over_time"]]
df_job_details.head(2)

,department,job_role,job_level,business_travel,over_time
0,Sales,Sales Executive,2,Travel_Rarely,True
1,Research & Development,Research Scientist,2,Travel_Frequently,False

In [13]:
df_job_details.to_csv("clean-data/df_job_details.csv",index=False)

In [ ]:
mycursor.execute("""
CREATE TABLE IF NOT EXISTS job_details (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(50) NOT NULL,
  `job_role` VARCHAR(50) NOT NULL,
  `job_level` INT NOT NULL,
  `business_travel` VARCHAR(50) NOT NULL,
  `over_time` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;
""")
cnx.commit()

print("Tabla job_details creada.")

Tabla job_details creada.

In [8]:
df_hr.columns

Index(['age', 'attrition', 'business_travel', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_number',
       'environment_satisfaction', 'gender', 'job_involvement', 'job_level',
       'job_role', 'job_satisfaction', 'marital_status', 'monthly_income',
       'monthly_rate', 'num_companies_worked', 'over_time',
       'percent_salary_hike', 'performance_rating',
       'relationship_satisfaction', 'total_working_years',
       'training_times_last_year', 'work_life_balance', 'years_at_company',
       'years_in_current_role', 'years_since_last_promotion',
       'years_with_curr_manager'],
      dtype='str')

In [9]:
df_career_history = df_hr[["total_working_years","years_at_company","years_in_current_role","years_since_last_promotion","years_with_curr_manager","num_companies_worked","training_times_last_year","attrition"]]
df_career_history.head(2)

,total_working_years,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager,num_companies_worked,training_times_last_year,attrition
0,8,6,4,0,5,8,0,True
1,10,10,7,1,7,1,3,False

In [14]:
df_career_history.to_csv("clean-data/df_career_history.csv",index=False)

In [52]:
mycursor.execute("""
CREATE TABLE IF NOT EXISTS career_history (
  `career_id` INT NOT NULL,
  `total_working_years` INT NOT NULL,
  `years_at_company` INT NOT NULL,
  `years_in_current_role` INT NOT NULL,
  `years_since_last_promotion` INT NOT NULL,
  `years_with_current_manager` INT NOT NULL,
  `num_companies_worked` INT NOT NULL,
  `training_times_last_year` INT NOT NULL,
  `attrition` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`career_id`))
ENGINE = InnoDB;
""")
cnx.commit()

print("Tabla career_history creada.")

Tabla career_history creada.

In [11]:
df_compensation = df_hr[["monthly_income","monthly_rate","percent_salary_hike"]]
df_compensation.head(2)

   monthly_income  monthly_rate  percent_salary_hike
0          5993.0         19479                   11
1          5130.0         24907                   23

In [15]:
df_compensation.to_csv("clean-data/df_compensation.csv",index=False)

In [53]:
mycursor.execute("""
CREATE TABLE IF NOT EXISTS compensation (
  `compensation_id` INT NOT NULL AUTO_INCREMENT,
  `monthly_income` INT NOT NULL,
  `monthly_rate` INT NOT NULL,
  `percent_salary_hike` INT NOT NULL,
  PRIMARY KEY (`compensation_id`))
ENGINE = InnoDB;
""")
cnx.commit()

print("Tabla compensation creada.")

Tabla compensation creada.

In [12]:
df_performance_satisfaction = df_hr[["performance_rating","job_involvement","environment_satisfaction","relationship_satisfaction","job_satisfaction","work_life_balance"]]
df_performance_satisfaction.head(2)

,performance_rating,job_involvement,environment_satisfaction,relationship_satisfaction,job_satisfaction,work_life_balance
0,3,3,2,1,4,1
1,4,2,3,4,2,3

In [16]:
df_performance_satisfaction.to_csv("clean-data/df_performance_satisfaction.csv",index=False)

In [54]:
mycursor.execute("""
CREATE TABLE IF NOT EXISTS performance_satisfaction (
  `performance_satisfaction_id` INT NOT NULL AUTO_INCREMENT,
  `performance_rating` INT NOT NULL,
  `job_involvement` INT NOT NULL,
  `environment_satisfaction` INT NOT NULL,
  `relationship_satisfaction` INT NOT NULL,
  `job_satisfaction` INT NOT NULL,
  `work_life_balance` INT NOT NULL,
  PRIMARY KEY (`performance_satisfaction_id`))
ENGINE = InnoDB;
""")
cnx.commit()

print("Tabla performance_satisfaction creada.")

Tabla performance_satisfaction creada.

In [55]:
mycursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
  `employee_number` VARCHAR(50) NOT NULL,
  `age` INT NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `marital_status` VARCHAR(40) NOT NULL,
  `education` VARCHAR(40) NOT NULL,
  `education_field` VARCHAR(70) NOT NULL,
  `distance_from_home` INT NOT NULL,
  `job_id` INT NOT NULL,
  `career_id` INT NOT NULL,
  `compensation_id` INT NOT NULL,
  `performance_satisfaction_id` INT NOT NULL,
  PRIMARY KEY (`employee_number`),
  INDEX `fk_employees_job_details_idx` (`job_id` ASC) VISIBLE,
  INDEX `fk_employees_career_history1_idx` (`career_id` ASC) VISIBLE,
  INDEX `fk_employees_compensation1_idx` (`compensation_id` ASC) VISIBLE,
  INDEX `fk_employees_performance_satisfaction1_idx` (`performance_satisfaction_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_job_details`
    FOREIGN KEY (`job_id`)
    REFERENCES `job_details` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_career_history1`
    FOREIGN KEY (`career_id`)
    REFERENCES `career_history` (`career_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_compensation1`
    FOREIGN KEY (`compensation_id`)
    REFERENCES `compensation` (`compensation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_performance_satisfaction1`
    FOREIGN KEY (`performance_satisfaction_id`)
    REFERENCES `performance_satisfaction` (`performance_satisfaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
""")
cnx.commit()

print("Tabla employees creada.")

Tabla employees creada.

In [25]:
with open("clean-data/df_job_details.csv", newline="", encoding="utf-8") as csvfile:
    reader = csv.DictReader(csvfile)
    print("Columnas CSV:", reader.fieldnames)

Columnas CSV: ['department', 'job_role', 'job_level', 'business_travel', 'over_time']

Insercion de datos en job_details

In [56]:
query_job = """
INSERT INTO job_details (
    department,
    job_role,
    job_level,
    business_travel,
    over_time
)
VALUES (%s, %s, %s, %s, %s)
"""

valores_job = [tuple(x) for x in df_job_details.to_numpy()]

mycursor.executemany(query_job, valores_job)
cnx.commit()

In [73]:
mycursor.execute("SELECT * FROM job_details")
job_details_IDs = mycursor.fetchall()
job_details_IDs

[(1, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (2,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Frequently',
  '0'),
 (3,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '1'),
 (4,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Frequently',
  '1'),
 (5,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (6,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Frequently',
  '0'),
 (7,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (8,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (9,
  'Research & Development',
  'Manufacturing Director',
  3,
  'Travel_Frequently',
  '0'),
 (10,
  'Research & Development',
  'Healthcare Representative',
  2,
  'Travel_Rarely',
  '0'),
 (11,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (12,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Rarely',
  '1'),
 (13, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (14,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (15,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '1'),
 (16,
  'Research & Development',
  'Manufacturing Director',
  3,
  'Travel_Rarely',
  '0'),
 (17, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '1'),
 (18, 'Research & Development', 'Laboratory Technician', 1, 'Non_Travel', '1'),
 (19, 'Sales', 'Manager', 4, 'Travel_Rarely', '0'),
 (20, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '1'),
 (21,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Non_Travel',
  '0'),
 (22, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '0'),
 (23, 'Research & Development', 'Research Director', 3, 'Travel_Rarely', '0'),
 (24, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (25, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (26, 'Research & Development', 'Manager', 5, 'Travel_Rarely', '0'),
 (27,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Frequently',
  '1'),
 (28, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (29,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Rarely',
  '0'),
 (30, 'Sales', 'Manager', 5, 'Travel_Rarely', '0'),
 (31,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (32,
  'Research & Development',
  'Healthcare Representative',
  2,
  'Travel_Rarely',
  '1'),
 (33,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (34, 'Sales', 'Sales Representative', 2, 'Travel_Rarely', '0'),
 (35, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '1'),
 (36, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (37, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '1'),
 (38, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '0'),
 (39, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '1'),
 (40, 'Sales', 'Sales Executive', 2, 'Travel_Frequently', '0'),
 (41,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (42,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (43,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (44, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (45,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Frequently',
  '0'),
 (46, 'Research & Development', 'Research Director', 5, 'Travel_Rarely', '0'),
 (47, 'Research & Development', 'Sales Executive', 2, 'Non_Travel', '0'),
 (48, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (49, 'Sales', 'Sales Executive', 2, 'Travel_Frequently', '1'),
 (50,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (51,
  'Research & Development',
  'Laboratory Technician',
  3,
  'Travel_Rarely',
  '1'),
 (52,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '1'),
 (53, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (54,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Non_Travel',
  '1'),
 (55, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (56,
  'Research & Development',
  'Research Director',
  3,
  'Travel_Frequently',
  '1'),
 (57, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (58,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '1'),
 (59,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Rarely',
  '0'),
 (60,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (61,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (62,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Frequently',
  '0'),
 (63, 'Research & Development', 'Research Director', 5, 'Travel_Rarely', '1'),
 (64, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (65,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Rarely',
  '0'),
 (66, 'Research & Development', 'Manager', 4, 'Travel_Rarely', '1'),
 (67,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Frequently',
  '0'),
 (68, 'Research & Development', 'Research Scientist', 3, 'Travel_Rarely', '0'),
 (69,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Frequently',
  '0'),
 (70, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '1'),
 (71, 'Sales', 'Sales Executive', 2, 'Travel_Frequently', '0'),
 (72, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (73, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (74, 'Research & Development', 'Research Scientist', 2, 'Travel_Rarely', '0'),
 (75,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (76,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (77, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (78, 'Research & Development', 'Research Director', 3, 'Travel_Rarely', '0'),
 (79, 'Research & Development', 'Research Director', 3, 'Travel_Rarely', '0'),
 (80, 'Human Resources', 'Human Resources', 2, 'Travel_Rarely', '1'),
 (81,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Rarely',
  '1'),
 (82, 'Research & Development', 'Research Scientist', 1, 'Travel_Rarely', '0'),
 (83, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (84, 'Research & Development', 'Research Scientist', 2, 'Non_Travel', '1'),
 (85,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (86,
  'Research & Development',
  'Manufacturing Director',
  3,
  'Travel_Rarely',
  '0'),
 (87, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '0'),
 (88,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (89,
  'Research & Development',
  'Healthcare Representative',
  2,
  'Travel_Rarely',
  '0'),
 (90, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (91,
  'Research & Development',
  'Healthcare Representative',
  4,
  'Travel_Frequently',
  '0'),
 (92, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (93, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (94,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Frequently',
  '1'),
 (95, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (96, 'Research & Development', 'Research Director', 3, 'Travel_Rarely', '0'),
 (97, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (98, 'Sales', 'Sales Executive', 2, 'Non_Travel', '0'),
 (99, 'Research & Development', 'Sales Executive', 4, 'Travel_Rarely', '0'),
 (100,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Non_Travel',
  '0'),
 (101, 'Human Resources', 'Human Resources', 1, 'Travel_Rarely', '0'),
 (102,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (103,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Frequently',
  '1'),
 (104,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Rarely',
  '0'),
 (105,
  'Research & Development',
  'Healthcare Representative',
  2,
  'Non_Travel',
  '0'),
 (106, 'Human Resources', 'Manager', 5, 'Non_Travel', '0'),
 (107,
  'Research & Development',
  'Research Director',
  5,
  'Travel_Frequently',
  '1'),
 (108, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (109,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (110,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (111,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Frequently',
  '0'),
 (112,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Frequently',
  '1'),
 (113, 'Human Resources', 'Manager', 4, 'Travel_Rarely', '1'),
 (114,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (115,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Rarely',
  '0'),
 (116, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (117, 'Research & Development', 'Manager', 3, 'Travel_Rarely', '0'),
 (118, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (119,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (120, 'Sales', 'Manager', 4, 'Travel_Frequently', '1'),
 (121,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Frequently',
  '0'),
 (122, 'Sales', 'Sales Executive', 2, 'Non_Travel', '0'),
 (123,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (124, 'Research & Development', 'Research Director', 5, 'Travel_Rarely', '0'),
 (125, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (126,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (127,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Rarely',
  '0'),
 (128, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '1'),
 (129,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (130,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (131,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Frequently',
  '0'),
 (132, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (133, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (134, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '1'),
 (135, 'Human Resources', 'Human Resources', 1, 'Travel_Rarely', '0'),
 (136,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (137,
  'Research & Development',
  'Manufacturing Director',
  3,
  'Travel_Frequently',
  '0'),
 (138, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (139, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (140, 'Human Resources', 'Human Resources', 2, 'Travel_Rarely', '1'),
 (141,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (142,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (143,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Rarely',
  '1'),
 (144,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (145, 'Sales', 'Sales Executive', 2, 'Travel_Frequently', '0'),
 (146,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (147,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (148, 'Research & Development', 'Manager', 4, 'Travel_Frequently', '0'),
 (149,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (150,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (151,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Frequently',
  '0'),
 (152, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (153, 'Sales', 'Sales Representative', 2, 'Travel_Rarely', '1'),
 (154,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Rarely',
  '0'),
 (155, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (156,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Non_Travel',
  '0'),
 (157,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (158,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (159, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (160, 'Sales', 'Sales Representative', 1, 'Travel_Frequently', '0'),
 (161,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (162, 'Research & Development', 'Research Scientist', 1, 'Non_Travel', '0'),
 (163,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (164,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Rarely',
  '1'),
 (165, 'Research & Development', 'Research Scientist', 1, 'Non_Travel', '1'),
 (166, 'Research & Development', 'Manager', 5, 'Travel_Rarely', '0'),
 (167,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (168, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (169, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (170,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (171,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (172, 'Sales', 'Sales Representative', 1, 'Travel_Frequently', '0'),
 (173,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (174,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Non_Travel',
  '0'),
 (175, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '1'),
 (176,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (177,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (178,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (179, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (180,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (181,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (182,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (183, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '1'),
 (184,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (185,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (186,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (187, 'Research & Development', 'Manager', 5, 'Travel_Rarely', '0'),
 (188, 'Research & Development', 'Research Director', 5, 'Travel_Rarely', '0'),
 (189,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Frequently',
  '0'),
 (190,
  'Research & Development',
  'Healthcare Representative',
  4,
  'Travel_Rarely',
  '0'),
 (191, 'Research & Development', 'Manager', 5, 'Travel_Rarely', '0'),
 (192,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (193,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '1'),
 (194, 'Research & Development', 'Research Scientist', 1, 'Non_Travel', '0'),
 (195, 'Research & Development', 'Manager', 4, 'Non_Travel', '0'),
 (196,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (197,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Frequently',
  '0'),
 (198,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Non_Travel',
  '0'),
 (199,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (200,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Rarely',
  '0'),
 (201,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Travel_Frequently',
  '0'),
 (202,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Non_Travel',
  '1'),
 (203,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Frequently',
  '1'),
 (204,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Rarely',
  '1'),
 (205,
  'Research & Development',
  'Healthcare Representative',
  2,
  'Travel_Rarely',
  '1'),
 (206, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (207,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (208,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Frequently',
  '0'),
 (209,
  'Research & Development',
  'Healthcare Representative',
  2,
  'Non_Travel',
  '0'),
 (210,
  'Research & Development',
  'Healthcare Representative',
  3,
  'Travel_Rarely',
  '0'),
 (211, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (212,
  'Research & Development',
  'Manufacturing Director',
  3,
  'Travel_Rarely',
  '0'),
 (213, 'Sales', 'Sales Executive', 2, 'Travel_Frequently', '0'),
 (214, 'Research & Development', 'Research Director', 3, 'Travel_Rarely', '0'),
 (215,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (216, 'Sales', 'Manager', 3, 'Travel_Rarely', '1'),
 (217, 'Sales', 'Sales Executive', 2, 'Travel_Frequently', '0'),
 (218,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (219, 'Sales', 'Sales Executive', 3, 'Non_Travel', '0'),
 (220, 'Sales', 'Sales Executive', 2, 'Travel_Rarely', '0'),
 (221,
  'Research & Development',
  'Laboratory Technician',
  2,
  'Travel_Rarely',
  '0'),
 (222,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (223,
  'Research & Development',
  'Research Director',
  3,
  'Travel_Frequently',
  '1'),
 (224, 'Sales', 'Sales Executive', 3, 'Travel_Rarely', '0'),
 (225,
  'Research & Development',
  'Manufacturing Director',
  2,
  'Non_Travel',
  '0'),
 (226,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '0'),
 (227, 'Sales', 'Sales Representative', 1, 'Travel_Frequently', '0'),
 (228, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (229, 'Sales', 'Sales Executive', 3, 'Travel_Frequently', '0'),
 (230,
  'Research & Development',
  'Research Scientist',
  1,
  'Travel_Rarely',
  '1'),
 (231,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (232, 'Research & Development', 'Manager', 5, 'Travel_Rarely', '0'),
 (233, 'Human Resources', 'Human Resources', 1, 'Travel_Rarely', '0'),
 (234, 'Sales', 'Manager', 5, 'Travel_Rarely', '0'),
 (235,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '1'),
 (236, 'Sales', 'Manager', 4, 'Travel_Rarely', '1'),
 (237,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (238, 'Sales', 'Manager', 5, 'Non_Travel', '1'),
 (239, 'Sales', 'Sales Representative', 1, 'Travel_Rarely', '0'),
 (240,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '1'),
 (241,
  'Research & Development',
  'Laboratory Technician',
  1,
  'Travel_Rarely',
  '0'),
 (242, 'Sales', 'Sales Executive', 2, 'Non_Travel', '0'),
 (243,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Rarely',
  '0'),
 (244,
  'Research & Development',
  'Research Scientist',
  2,
  'Travel_Rarely',
  '0'),

In [33]:
df_job_details.columns

Index(['department', 'job_role', 'job_level', 'business_travel', 'over_time'], dtype='str')

In [74]:
df_job_details_IDs = pd.DataFrame(job_details_IDs,columns=['job_id', 'department', 'job_role', 'job_level', 'business_travel', 'over_time'])
df_job_details_IDs

,job_id,department,job_role,job_level,business_travel,over_time
0,1,Sales,Sales Executive,2,Travel_Rarely,1
1,2,Research & Development,Research Scientist,2,Travel_Frequently,0
2,3,Research & Development,Laboratory Technician,1,Travel_Rarely,1
3,4,Research & Development,Research Scientist,1,Travel_Frequently,1
4,5,Research & Development,Laboratory Technician,1,Travel_Rarely,0
...,...,...,...,...,...,...
1465,1466,Research & Development,Laboratory Technician,2,Travel_Frequently,0
1466,1467,Research & Development,Healthcare Representative,3,Travel_Rarely,0
1467,1468,Research & Development,Manufacturing Director,2,Travel_Rarely,1
1468,1469,Sales,Sales Executive,2,Travel_Frequently,0
1469,1470,Research & Development,Laboratory Technician,2,Travel_Rarely,0

In [62]:
df_job_details_IDs.columns

Index(['job_id', 'department', 'job_role', 'job_level', 'business_travel',
       'over_time'],
      dtype='str')

In [64]:
df_hr.columns

Index(['age', 'attrition', 'business_travel', 'department',
       'distance_from_home', 'education', 'education_field', 'employee_number',
       'environment_satisfaction', 'gender', 'job_involvement', 'job_level',
       'job_role', 'job_satisfaction', 'marital_status', 'monthly_income',
       'monthly_rate', 'num_companies_worked', 'over_time',
       'percent_salary_hike', 'performance_rating',
       'relationship_satisfaction', 'total_working_years',
       'training_times_last_year', 'work_life_balance', 'years_at_company',
       'years_in_current_role', 'years_since_last_promotion',
       'years_with_curr_manager'],
      dtype='str')

In [67]:
df_hr[['department', 'job_role', 'job_level', 'business_travel', 'over_time']].head(2)

,department,job_role,job_level,business_travel,over_time
0,Sales,Sales Executive,2,Travel_Rarely,True
1,Research & Development,Research Scientist,2,Travel_Frequently,False

In [68]:
df_job_details_IDs[['department', 'job_role', 'job_level', 'business_travel', 'over_time']].head(2)

,department,job_role,job_level,business_travel,over_time
0,Sales,Sales Executive,2,Travel_Rarely,1
1,Research & Development,Research Scientist,2,Travel_Frequently,0

In [75]:
df_job_details_IDs["over_time"] = df_job_details_IDs["over_time"].replace({"1":True,"0":False})

In [ ]:
# Hacemos merge con el df_hr y el df_job_details_IDs:

df_hr = df_hr.merge(df_job_details_IDs,on=['department', 'job_role', 'job_level', 'business_travel', 'over_time'],how="left")

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,...,performance_rating,relationship_satisfaction,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager,job_id
0,41,True,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,...,3,1,8,0,1,6,4,0,5,1
1,41,True,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,...,3,1,8,0,1,6,4,0,5,53
2,41,True,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,...,3,1,8,0,1,6,4,0,5,55
3,41,True,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,...,3,1,8,0,1,6,4,0,5,92
4,41,True,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,...,3,1,8,0,1,6,4,0,5,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65887,34,False,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,...,3,1,6,3,4,4,3,1,2,1131
65888,34,False,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,...,3,1,6,3,4,4,3,1,2,1156
65889,34,False,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,...,3,1,6,3,4,4,3,1,2,1209
65890,34,False,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,...,3,1,6,3,4,4,3,1,2,1342
65891,34,False,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,...,3,1,6,3,4,4,3,1,2,1470

In [ ]:
for employee_data in reader:
    employee_data = employee_data.get("employee_number")

    employee_number = employee_data.get("employee_number")
    age = employee_data.get("age")
    gender = employee_data.get("gender")
    marital_status = employee_data.get("marital_status")
    distance_from_home = employee_data.get("distance_from_home")
    education = employee_data.get("education")
    education_field = employee_data.get("education_field")


    mycursor.execute(
        """
        INSERT INTO employees (employee_number, age, gender, marital_status, distance_from_home, education, education_field)
        VALUES (%s, %s, %s)
        ON DUPLICATE KEY UPDATE
          numero_reproducciones = VALUES(numero_reproducciones),
          numero_oyentes = VALUES(numero_oyentes)
        """,
        (nombre, playcount, listeners)
    )

cnx.commit()
print("Artistas insertados.")